#!/usr/bin/env bun
/**
 * Claude Code -> OpenAI Codex harness adapter (D-9).
 *
 * `.claude/**` is the ONLY hand-edited harness source. This script projects it onto the files
 * Codex CLI actually reads, so neither harness is second-class and nothing is maintained twice:
 *
 *   CLAUDE.md + .claude/rules/*.md  ->  AGENTS.md            (inlined: Codex has no @-imports)
 *   .claude/agents/*.md             ->  .codex/agents/*.toml (frontmatter+body -> TOML)
 *   .claude/hooks/*.sh              ->  .codex/hooks.json    (SAME scripts, Codex tool matchers)
 *   .mcp.json                       ->  .codex/config.toml   ([mcp_servers.<name>])
 *   .claude/settings.json           ->  .codex/config.toml   (filesystem permission profile)
 *   .claude/settings.json           ->  .codex/rules/*.rules (Bash allow/ask exec policy)
 *   .claude/skills/<n>/             ->  .agents/skills/<n>   (symlink — zero copy)
 *
 * Usage:
 *   bun run sync-codex          write the Codex mirror
 *   bun run sync-codex --check  fail (exit 1) if the mirror is stale — used by validate.sh
 *
 * Verified against codex-cli 0.144.6 (2026-07-28). See docs/developers/runbooks/codex-parity.md
 * for the schema sources and the porting recipe.
 */

import {
  readdirSync,
  readFileSync,
  existsSync,
  mkdirSync,
  symlinkSync,
  readlinkSync,
  rmSync,
  lstatSync,
} from "node:fs";
import { join, relative, dirname } from "node:path";

const ROOT = join(import.meta.dir, "..");
const CHECK = process.argv.includes("--check");
const SUPPORTED_CODEX_VERSION = "0.144.6";

/** Codex refuses to grow the instruction chain past project_doc_max_bytes (32 KiB default). */
const AGENTS_MD_MAX_BYTES = 32 * 1024;

/** Order matters only for readability; it mirrors the order CLAUDE.md names the rules in. */
const RULE_ORDER = ["spec-authority", "no-custody", "no-market-metrics", "versions-pinned"];

// ---------------------------------------------------------------------------- helpers

const read = (p: string) => readFileSync(join(ROOT, p), "utf8");
const banner = (src: string) =>
  `<!-- GENERATED by scripts/sync-codex.ts — DO NOT EDIT.\n` +
  `     Source of truth: ${src}\n` +
  `     Regenerate with \`bun run sync-codex\`; \`bun run validate\` fails on drift. -->\n`;

/** Minimal frontmatter reader for the YAML subset the .claude/agents/*.md files use. */
function parseFrontmatter(raw: string): { fields: Record<string, string>; body: string } {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!m) throw new Error("missing YAML frontmatter");
  const fm = m[1];
  const body = m[2];
  if (fm === undefined || body === undefined) throw new Error("invalid YAML frontmatter");
  const fields: Record<string, string> = {};
  let key: string | null = null;
  let folded: string[] = [];
  const flush = () => {
    if (key) fields[key] = folded.join(" ").replace(/\s+/g, " ").trim();
    key = null;
    folded = [];
  };
  for (const line of fm.split(/\r?\n/)) {
    const kv = line.match(/^([A-Za-z_][\w-]*):\s*(.*)$/);
    if (kv) {
      flush();
      const k = kv[1];
      const v = kv[2];
      if (k === undefined || v === undefined) throw new Error("invalid YAML frontmatter field");
      if (v === ">" || v === ">-" || v === "|" || v === "|-") key = k;
      else fields[k] = v.trim();
    } else if (key && line.trim()) {
      folded.push(line.trim());
    }
  }
  flush();
  return { fields, body: body.trim() };
}

/** Demote every ATX heading by `by` levels so inlined content nests under its host section. */
const demote = (md: string, by: number) =>
  md.replace(/^(#{1,5}) /gm, (_, h: string) => "#".repeat(Math.min(6, h.length + by)) + " ");

/** TOML multi-line literal string — no escape processing, so content passes through verbatim. */
function tomlLiteral(s: string): string {
  if (s.includes("'''")) throw new Error("content contains ''' — cannot use a TOML literal string");
  return `'''\n${s}\n'''`;
}

const tomlBasic = (s: string) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

type ClaudeSettings = {
  permissions?: {
    deny?: string[];
    ask?: string[];
    allow?: string[];
  };
};

const settings = JSON.parse(read(".claude/settings.json")) as ClaudeSettings;

function claudeReadDenyGlobs(): string[] {
  return (settings.permissions?.deny ?? [])
    .map((rule) => rule.match(/^Read\((.+)\)$/)?.[1])
    .filter((glob): glob is string => Boolean(glob))
    .sort();
}

type BashPolicy = { command: string[]; decision: "allow" | "prompt"; source: string };

function claudeBashPolicies(): BashPolicy[] {
  const translate = (rules: string[], decision: BashPolicy["decision"]): BashPolicy[] =>
    rules.map((source) => {
      const raw = source.match(/^Bash\((.+)\)$/)?.[1];
      if (!raw) throw new Error(`unsupported Claude permission rule: ${source}`);
      const commandText = raw.endsWith("*") ? raw.slice(0, -1).trimEnd() : raw;
      if (!commandText || /[|;&<>()$`"'\\]/.test(commandText))
        throw new Error(`unsafe/unsupported Bash permission rule: ${source}`);
      return { command: commandText.split(/\s+/), decision, source };
    });

  return [
    ...translate(settings.permissions?.allow ?? [], "allow"),
    ...translate(settings.permissions?.ask ?? [], "prompt"),
  ].sort((a, b) => a.command.join(" ").localeCompare(b.command.join(" ")));
}

// ---------------------------------------------------------------------------- generators

function buildAgentsMd(): string {
  const claude = read("CLAUDE.md").trim();
  const rules = RULE_ORDER.map((slug) => {
    const raw = read(`.claude/rules/${slug}.md`).trim();
    const title = raw.match(/^#\s+(.+)$/m)?.[1] ?? slug;
    const body = demote(raw.replace(/^#\s+.+\r?\n/, "").trim(), 3);
    return `### Rule: \`${slug}\` — ${title}\n\n_Source: \`.claude/rules/${slug}.md\` (verbatim)._\n\n${body}`;
  }).join("\n\n");

  return `${banner("CLAUDE.md + .claude/rules/*.md")}
${claude}

---

## Always-on rules (inlined for Codex)

In Claude Code these four load automatically from \`.claude/rules/\`. Codex can follow ordinary
file references, but it does not eagerly assemble Claude's \`@path\` imports or auto-load that
rules directory, so always-on rules are inlined here verbatim. They are not advisory: violating
one is a bug. The source of truth remains \`.claude/rules/**\` — edit there, then run
\`bun run sync-codex\`.

${rules}

---

## Harness asset map

This repo is maintained for two agent harnesses from one source. Everything under \`.claude/\` is
hand-edited; everything in the Codex column is generated by \`scripts/sync-codex.ts\`.

| Concern      | Claude Code (source)      | Codex (generated)      | How it is kept in sync                   |
| ------------ | ------------------------- | ---------------------- | ---------------------------------------- |
| Instructions | \`CLAUDE.md\`               | \`AGENTS.md\`            | rules inlined (no \`@\`-imports in Codex)  |
| Rules        | \`.claude/rules/*.md\`      | inlined above          | same text, demoted headings              |
| Subagents    | \`.claude/agents/*.md\`     | \`.codex/agents/*.toml\` | body -> \`developer_instructions\`         |
| Skills       | \`.claude/skills/*/\`       | \`.agents/skills/*\`     | **symlink** — one copy on disk           |
| Hooks        | \`.claude/hooks/*.sh\`      | \`.codex/hooks.json\`    | **same scripts**, Codex tool matchers    |
| MCP          | \`.mcp.json\`               | \`.codex/config.toml\`   | \`[mcp_servers.<name>]\`                   |
| Permissions  | \`.claude/settings.json\`   | \`.codex/config.toml\`   | filesystem permission profile           |
| Shell policy | \`.claude/settings.json\`   | \`.codex/rules/*.rules\` | exec-policy prefixes                     |

Codex-specific notes: hooks require one-time trust (\`/hooks\` in the TUI, or
\`--dangerously-bypass-hook-trust\` in CI), and project-scoped \`.codex/\` config loads only for a
trusted project.
`;
}

function buildCodexAgents(): Map<string, string> {
  const out = new Map<string, string>();
  for (const file of readdirSync(join(ROOT, ".claude/agents"))
    .filter((f) => f.endsWith(".md"))
    .sort()) {
    const { fields, body } = parseFrontmatter(read(`.claude/agents/${file}`));
    const name = fields.name ?? file.replace(/\.md$/, "");
    const tools = fields.tools ?? "";
    // Codex lacks Claude's general built-in-tool allowlist. The security property this repo needs
    // is enforceable, though: omission of write tools becomes the built-in read-only permission
    // profile, with prose retained as defense in depth.
    const readOnly = tools !== "" && !/\b(Write|Edit|MultiEdit)\b/.test(tools);
    const instructions =
      body +
      (readOnly
        ? `\n\n## Harness constraint (Codex)\n\nYou are a READ-ONLY agent. Never create, edit, or delete a file, and never run a command that ` +
          `mutates the working tree. Report findings; the main thread or another agent applies them. ` +
          `(Claude enforces this through the tool allowlist \`${tools}\`; Codex additionally starts ` +
          `this role with \`default_permissions = ":read-only"\`.)`
        : "");

    out.set(
      `.codex/agents/${name}.toml`,
      `# GENERATED by scripts/sync-codex.ts from .claude/agents/${file} — DO NOT EDIT.\n` +
        `# Regenerate with \`bun run sync-codex\`.\n\n` +
        `name = ${tomlBasic(name)}\n` +
        `description = ${tomlBasic(fields.description ?? "")}\n` +
        (readOnly ? `default_permissions = ":read-only"\n` : "") +
        `\n` +
        `developer_instructions = ${tomlLiteral(instructions)}\n`,
    );
  }
  return out;
}

/**
 * Codex tool names differ from Claude's and are not fully documented, so matchers are permissive
 * regexes covering both harnesses' names. The hook SCRIPTS are shared verbatim — they read the
 * same stdin JSON contract (tool_name / tool_input / stop_hook_active) and use the same exit-2
 * blocking semantics in both harnesses.
 */
function buildHooksJson(): string {
  const run = (script: string) =>
    `bash -c 'cd "$(git rev-parse --show-toplevel 2>/dev/null || pwd)" && exec ./.claude/hooks/${script}'`;

  return (
    JSON.stringify(
      {
        _generated: "by scripts/sync-codex.ts — DO NOT EDIT. Run `bun run sync-codex`.",
        hooks: {
          PreToolUse: [
            {
              matcher: "(?i)^(bash|shell|unified_exec|exec_command|local_shell)$",
              hooks: [
                {
                  type: "command",
                  command: run("protect-secrets.sh"),
                  statusMessage: "rob-mcp: secret/destructive-command guard",
                },
              ],
            },
            {
              matcher: "(?i)^(apply_patch|write|edit|multiedit|edit_file|create_file)$",
              hooks: [
                {
                  type: "command",
                  command: run("protect-generated.sh"),
                  statusMessage: "rob-mcp: generated harness guard",
                },
              ],
            },
          ],
          PostToolUse: [
            {
              matcher: "(?i)^(apply_patch|write|edit|multiedit|edit_file|create_file)$",
              hooks: [
                {
                  type: "command",
                  command: run("check-hard-rules.sh"),
                  statusMessage: "rob-mcp: hard-rule scan",
                },
              ],
            },
          ],
          Stop: [
            {
              hooks: [
                {
                  type: "command",
                  command: run("stop-typecheck.sh"),
                  timeout: 240,
                  statusMessage: "rob-mcp: typecheck",
                },
              ],
            },
          ],
        },
      },
      null,
      2,
    ) + "\n"
  );
}

function buildCodexConfig(): string {
  const mcp = JSON.parse(read(".mcp.json")).mcpServers ?? {};
  const servers = Object.entries(mcp as Record<string, any>)
    .map(([name, cfg]) => {
      const lines = [`[mcp_servers.${name}]`];
      if (cfg.url) lines.push(`url = ${tomlBasic(cfg.url)}`);
      if (cfg.command) lines.push(`command = ${tomlBasic(cfg.command)}`);
      if (Array.isArray(cfg.args) && cfg.args.length)
        lines.push(`args = [${cfg.args.map(tomlBasic).join(", ")}]`);
      if (cfg.url === "https://mcp.context7.com/mcp") {
        lines.push(`required = false`);
        lines.push(
          `env_http_headers = { ${tomlBasic("CONTEXT7_API_KEY")} = ${tomlBasic("CONTEXT7_API_KEY")} }`,
        );
      }
      return lines.join("\n");
    })
    .join("\n\n");

  const denyGlobs = claudeReadDenyGlobs();
  const permissions =
    `default_permissions = "rob-mcp"\n\n` +
    `[permissions.rob-mcp]\n` +
    `description = "Generated from .claude/settings.json: workspace editing with secret paths denied."\n` +
    `extends = ":workspace"\n\n` +
    `[permissions.rob-mcp.filesystem]\n` +
    `glob_scan_max_depth = 8\n\n` +
    `[permissions.rob-mcp.filesystem.":workspace_roots"]\n` +
    denyGlobs.map((glob) => `${tomlBasic(glob)} = "deny"`).join("\n");

  return (
    `# GENERATED by scripts/sync-codex.ts from .mcp.json + .claude/settings.json — DO NOT EDIT.\n` +
    `# Regenerate with \`bun run sync-codex\`; \`bun run validate\` fails on drift.\n` +
    `# Project-scoped config loads only when this project is trusted by Codex.\n\n` +
    `# Hooks live in .codex/hooks.json (same scripts as .claude/hooks/). They require one-time\n` +
    `# trust approval via \`/hooks\` in the TUI, or --dangerously-bypass-hook-trust in CI.\n\n` +
    `${permissions}\n\n` +
    `${servers}\n`
  );
}

function buildCodexRules(): string {
  const rules = claudeBashPolicies()
    .map(({ command, decision, source }) => {
      const commandText = command.join(" ");
      return (
        `# Source: ${source}\n` +
        `prefix_rule(\n` +
        `    pattern = [${command.map(tomlBasic).join(", ")}],\n` +
        `    decision = ${tomlBasic(decision)},\n` +
        `    justification = ${tomlBasic(`Generated from Claude permission rule ${source}.`)},\n` +
        `    match = [${tomlBasic(commandText)}],\n` +
        `)\n`
      );
    })
    .join("\n");

  return (
    `# GENERATED by scripts/sync-codex.ts from .claude/settings.json — DO NOT EDIT.\n` +
    `# Regenerate with \`bun run sync-codex\`.\n\n` +
    rules
  );
}

function buildParityManifest(): string {
  return (
    JSON.stringify(
      {
        generatedBy: "scripts/sync-codex.ts",
        supportedCodexVersion: SUPPORTED_CODEX_VERSION,
        sourceFiles: ["CLAUDE.md", ".claude/**", ".mcp.json"],
      },
      null,
      2,
    ) + "\n"
  );
}

// ---------------------------------------------------------------------------- run

const files = new Map<string, string>([
  ["AGENTS.md", buildAgentsMd()],
  [".codex/hooks.json", buildHooksJson()],
  [".codex/config.toml", buildCodexConfig()],
  [".codex/rules/rob-mcp.rules", buildCodexRules()],
  [".codex/parity.json", buildParityManifest()],
  ...buildCodexAgents(),
]);

const agentsBytes = Buffer.byteLength(files.get("AGENTS.md")!, "utf8");
if (agentsBytes > AGENTS_MD_MAX_BYTES) {
  console.error(
    `sync-codex: AGENTS.md is ${agentsBytes} bytes, over Codex's ${AGENTS_MD_MAX_BYTES}-byte ` +
      `project_doc_max_bytes — Codex would silently truncate the instruction chain. Trim CLAUDE.md ` +
      `or the rules.`,
  );
  process.exit(1);
}

// Skills: symlinked rather than copied, so there is exactly one SKILL.md on disk per skill.
const skills = existsSync(join(ROOT, ".claude/skills"))
  ? readdirSync(join(ROOT, ".claude/skills"))
      .filter((d) => existsSync(join(ROOT, ".claude/skills", d, "SKILL.md")))
      .sort()
  : [];

const stale: string[] = [];

for (const [path, content] of files) {
  const abs = join(ROOT, path);
  const current = existsSync(abs) ? readFileSync(abs, "utf8") : null;
  if (current === content) continue;
  stale.push(path);
  if (!CHECK) {
    mkdirSync(dirname(abs), { recursive: true });
    Bun.write(abs, content);
  }
}

for (const skill of skills) {
  const link = join(ROOT, ".agents/skills", skill);
  const target = relative(dirname(link), join(ROOT, ".claude/skills", skill));
  let current: string | null = null;
  try {
    current = lstatSync(link).isSymbolicLink() ? readlinkSync(link) : "<not a symlink>";
  } catch {
    current = null;
  }
  if (current === target) continue;
  stale.push(`.agents/skills/${skill} -> ${target}`);
  if (!CHECK) {
    mkdirSync(dirname(link), { recursive: true });
    if (current !== null) rmSync(link, { recursive: true, force: true });
    symlinkSync(target, link);
  }
}

// Orphans: a Codex mirror file whose .claude/ source was deleted or renamed.
const orphanDirs: Array<[string, (f: string) => boolean]> = [
  [".codex/agents", (f) => f.endsWith(".toml") && !files.has(`.codex/agents/${f}`)],
  [".codex/rules", (f) => f.endsWith(".rules") && !files.has(`.codex/rules/${f}`)],
  [".agents/skills", (f) => !skills.includes(f)],
];
for (const [dir, isOrphan] of orphanDirs) {
  if (!existsSync(join(ROOT, dir))) continue;
  for (const f of readdirSync(join(ROOT, dir)).filter(isOrphan)) {
    stale.push(`${dir}/${f} (orphan — source removed)`);
    if (!CHECK) rmSync(join(ROOT, dir, f), { recursive: true, force: true });
  }
}

if (CHECK) {
  if (stale.length) {
    console.error(
      "sync-codex --check: Codex mirror is STALE. Run `bun run sync-codex` and commit:",
    );
    for (const p of stale) console.error(`  - ${p}`);
    process.exit(1);
  }
  console.log(
    `sync-codex --check: OK (AGENTS.md ${agentsBytes}B, ${skills.length} skills, ${files.size} files)`,
  );
} else {
  console.log(
    stale.length
      ? `sync-codex: wrote ${stale.length} file(s):\n${stale.map((p) => `  - ${p}`).join("\n")}`
      : "sync-codex: already up to date",
  );
  console.log(`sync-codex: AGENTS.md ${agentsBytes}B / ${AGENTS_MD_MAX_BYTES}B budget`);
}
